"""
Scalping signals: generates high-frequency BUY/SELL/HOLD calls with
precise entry price, take-profit, and stop-loss levels.

Each sub-signal votes independently. A trade is only triggered when
at least SCALP_MIN_SIGNAL_SCORE indicators agree (default 3 of 5).

Returned ScalpSignal dict
    action          : "BUY" | "SELL" | "HOLD"
    score           : int   — number of indicators that agree
    entry_price     : float
    take_profit     : float
    stop_loss       : float
    tp_pct          : float — % gain to TP
    sl_pct          : float — % loss to SL
    risk_reward     : float — TP distance / SL distance
    reasons         : list[str]
    indicator_votes : dict[str, str]  — per-indicator BUY/SELL/HOLD

ScalpTradeLog entries are generated by scan_scalp_signals() by walking
the historical DataFrame and marking every entry/exit event.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

import pandas as pd

from core.config import (
    BROKER_COMMISSION,
    SCALP_ATR_PERIOD,
    SCALP_EMA_FAST,
    SCALP_EMA_SLOW,
    SCALP_MIN_SIGNAL_SCORE,
    SCALP_RSI_BUY,
    SCALP_RSI_PERIOD,
    SCALP_RSI_SELL,
    SCALP_STOP_PCT,
    SCALP_TARGET_PCT,
    SELL_TAX_RATE,
)

Action = Literal["BUY", "SELL", "HOLD"]

# ── Helpers ───────────────────────────────────────────────────────────────────

def _last(df: pd.DataFrame, col: str):
    """Safe last non-null value access."""
    return df[col].dropna().iloc[-1] if col in df.columns and not df[col].dropna().empty else None


def _tp_sl(
    action: Action,
    price: float,
    atr: float | None,
    tp_pct: float,
    sl_pct: float,
) -> tuple[float, float]:
    """Compute take-profit and stop-loss prices.
    Uses ATR-based sizing when available, otherwise fixed %.
    """
    if atr and atr > 0:
        tp_dist = max(atr * 1.5, price * tp_pct)
        sl_dist = max(atr * 0.8, price * sl_pct)
    else:
        tp_dist = price * tp_pct
        sl_dist = price * sl_pct

    if action == "BUY":
        return round(price + tp_dist, 0), round(price - sl_dist, 0)
    return round(price - tp_dist, 0), round(price + sl_dist, 0)


# ── Individual indicator votes ────────────────────────────────────────────────

def _ema_vote(df: pd.DataFrame) -> tuple[Action, str]:
    fast = _last(df, f"EMA_{SCALP_EMA_FAST}")
    slow = _last(df, f"EMA_{SCALP_EMA_SLOW}")
    if fast is None or slow is None:
        return "HOLD", "EMA data missing"
    if fast > slow:
        diff_pct = (fast - slow) / slow * 100
        return "BUY",  f"EMA{SCALP_EMA_FAST} > EMA{SCALP_EMA_SLOW} (+{diff_pct:.3f}%)"
    if fast < slow:
        diff_pct = (slow - fast) / slow * 100
        return "SELL", f"EMA{SCALP_EMA_FAST} < EMA{SCALP_EMA_SLOW} (-{diff_pct:.3f}%)"
    return "HOLD", "EMA flat"


def _rsi_vote(df: pd.DataFrame) -> tuple[Action, str]:
    rsi = _last(df, f"RSI_{SCALP_RSI_PERIOD}")
    if rsi is None:
        return "HOLD", "RSI data missing"
    if rsi < SCALP_RSI_BUY:
        return "BUY",  f"RSI oversold ({rsi:.1f} < {SCALP_RSI_BUY})"
    if rsi > SCALP_RSI_SELL:
        return "SELL", f"RSI overbought ({rsi:.1f} > {SCALP_RSI_SELL})"
    return "HOLD", f"RSI neutral ({rsi:.1f})"


def _vwap_vote(df: pd.DataFrame) -> tuple[Action, str]:
    price = _last(df, "Close")
    vwap  = _last(df, "VWAP")
    if price is None or vwap is None:
        return "HOLD", "VWAP data missing"
    diff_pct = (price - vwap) / vwap * 100
    if price > vwap:
        return "BUY",  f"Price above VWAP (+{diff_pct:.3f}%)"
    if price < vwap:
        return "SELL", f"Price below VWAP ({diff_pct:.3f}%)"
    return "HOLD", "Price at VWAP"


def _stoch_vote(df: pd.DataFrame) -> tuple[Action, str]:
    k = _last(df, "Stoch_K")
    d = _last(df, "Stoch_D")
    if k is None or d is None:
        return "HOLD", "Stochastic data missing"
    if k < 20 and d < 20:
        return "BUY",  f"Stoch oversold K={k:.1f} D={d:.1f}"
    if k > 80 and d > 80:
        return "SELL", f"Stoch overbought K={k:.1f} D={d:.1f}"
    if k > d:
        return "BUY",  f"Stoch %K crossed above %D ({k:.1f} > {d:.1f})"
    if k < d:
        return "SELL", f"Stoch %K crossed below %D ({k:.1f} < {d:.1f})"
    return "HOLD", f"Stoch neutral K={k:.1f}"


def _momentum_vote(df: pd.DataFrame) -> tuple[Action, str]:
    mom = _last(df, "Momentum_3")
    if mom is None:
        return "HOLD", "Momentum data missing"
    if mom > 0.1:
        return "BUY",  f"3-bar momentum positive ({mom:+.3f}%)"
    if mom < -0.1:
        return "SELL", f"3-bar momentum negative ({mom:+.3f}%)"
    return "HOLD", f"3-bar momentum flat ({mom:+.3f}%)"


# ── Main signal function ──────────────────────────────────────────────────────

def scalp_signal(
    df: pd.DataFrame,
    tp_pct: float = SCALP_TARGET_PCT,
    sl_pct: float = SCALP_STOP_PCT,
) -> dict:
    """Generate a scalp signal dict from the latest bar of an enriched DataFrame."""
    votes_raw: dict[str, tuple[Action, str]] = {
        "EMA crossover": _ema_vote(df),
        "RSI (7)":       _rsi_vote(df),
        "VWAP":          _vwap_vote(df),
        "Stochastic":    _stoch_vote(df),
        "Momentum":      _momentum_vote(df),
    }

    buy_score  = sum(1 for a, _ in votes_raw.values() if a == "BUY")
    sell_score = sum(1 for a, _ in votes_raw.values() if a == "SELL")
    max_score  = max(buy_score, sell_score)

    if max_score < SCALP_MIN_SIGNAL_SCORE:
        action: Action = "HOLD"
    elif buy_score > sell_score:
        action = "BUY"
    else:
        action = "SELL"

    price = _last(df, "Close") or 0.0
    atr   = _last(df, f"ATR_{SCALP_ATR_PERIOD}")
    tp, sl = _tp_sl(action, price, atr, tp_pct, sl_pct)

    tp_pct_actual = abs(tp - price) / price * 100 if price else 0.0
    sl_pct_actual = abs(sl - price) / price * 100 if price else 0.0
    rr = tp_pct_actual / sl_pct_actual if sl_pct_actual else 0.0

    # Net profit accounting for taxes + commission
    total_cost_pct = (SELL_TAX_RATE + BROKER_COMMISSION * 2) * 100
    net_tp_pct = tp_pct_actual - total_cost_pct

    reasons = [reason for _, reason in votes_raw.values() if "missing" not in reason]

    return {
        "action":           action,
        "score":            max_score,
        "max_possible":     len(votes_raw),
        "entry_price":      price,
        "take_profit":      tp,
        "stop_loss":        sl,
        "tp_pct":           round(tp_pct_actual, 3),
        "sl_pct":           round(sl_pct_actual, 3),
        "net_tp_pct":       round(net_tp_pct, 3),
        "risk_reward":      round(rr, 2),
        "total_cost_pct":   round(total_cost_pct, 3),
        "reasons":          reasons,
        "indicator_votes":  {k: v[0] for k, v in votes_raw.items()},
        "vote_reasons":     {k: v[1] for k, v in votes_raw.items()},
        "atr":              round(atr, 2) if atr else None,
    }


# ── Historical trade log ──────────────────────────────────────────────────────

def scan_scalp_signals(
    df: pd.DataFrame,
    tp_pct: float = SCALP_TARGET_PCT,
    sl_pct: float = SCALP_STOP_PCT,
    min_score: int = SCALP_MIN_SIGNAL_SCORE,
) -> pd.DataFrame:
    """Walk the DataFrame bar-by-bar and record every BUY/SELL event.

    Returns a DataFrame of trade events with columns:
        datetime, action, price, take_profit, stop_loss, score, reason_summary
    """
    events = []
    for i in range(20, len(df)):  # need at least 20 bars for indicator warmup
        window = df.iloc[:i + 1]
        sig = scalp_signal(window, tp_pct=tp_pct, sl_pct=sl_pct)
        if sig["action"] != "HOLD" and sig["score"] >= min_score:
            events.append({
                "datetime":      df.index[i],
                "action":        sig["action"],
                "price":         sig["entry_price"],
                "take_profit":   sig["take_profit"],
                "stop_loss":     sig["stop_loss"],
                "tp_pct":        sig["tp_pct"],
                "sl_pct":        sig["sl_pct"],
                "net_tp_pct":    sig["net_tp_pct"],
                "risk_reward":   sig["risk_reward"],
                "score":         sig["score"],
                "reason_summary": " | ".join(sig["reasons"][:2]),
            })

    if not events:
        return pd.DataFrame()

    log = pd.DataFrame(events).set_index("datetime")

    # De-duplicate: drop consecutive same-action signals (keep first)
    log = log[log["action"] != log["action"].shift()]
    return log
